//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Girafile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentDate
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> IDDocument { get; set; }
        public string Name { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<bool> NotificationSent { get; set; }
    
        public virtual Document Document { get; set; }
    }
}
