//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Girafile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public System.Guid ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.Guid> IDAction { get; set; }
        public Nullable<System.Guid> IDDocument { get; set; }
    
        public virtual Action Action { get; set; }
        public virtual Document Document { get; set; }
    }
}
